language: python
python:
  - "3.7"
addons:
  - postgres: "11"
sudo: false
cache: pip
before_script:
  - psql -c 'create database garfield;' -U postgres
  - psql -c 'create database fsmi;' -U postgres
  - ./scripts/fill_data.py
script: ./scripts/run_tests.sh
